version: "1.5.0-{build}"

platform: x64

init:
  - git config --global core.autocrlf input
    # TODO: Needs select-str to get version from package.json to save in env and update below
    #  - ps: Update-AppveyorBuild -Version "0.1.9-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))-Windows"
    #  - set BUILDVER=%APPVEYOR_BUILD_VERSION%-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))

cache:
    #  - node_modules
    #  - '%APPDATA%\npm-cache'
    #  - '%USERPROFILE%\.electron'
    #  - $HOME/.cache/electron
    #  - $HOME/.cache/electron-builder
    #  - $HOME/.npm/_prebuilds

clone_folder: c:\projects\dart

environment:
  access_token:
    secure: "0muZEDVGEpw8OhnyWFnafYkUgrt+7kl6MdWEA2guW8oLX6s3dMoRrhQjuF3Sbpi5"
  node_path: %USERPROFILE%\AppData\Roaming\npm\node_modules
#  artifactName: DARTtest.Setup.0.1.8.$(APPVEYOR_BUILD_VERSION).$(APPVEYOR_REPO_COMMIT).exe

install:
  - ps: Install-Product node ''
  - git reset --hard HEAD
  - npm install --global npm@latest
    #  - npm install electron-builder@next # force install next version to test electron-builder
  - npm install --global jest
  - set PATH=%APPVEYOR_BUILD_FOLDER%/node_modules/.bin;%APPVEYOR_BUILD_FOLDER%/node_modules/;%PATH%
  - echo %PATH%
  - npm install

build_script:
  - npm test --
    #- cd %APPVEYOR_BUILD_FOLDER%/electron && electron-builder .

#artifacts:
#  - file: electron/dist/*.exe
#    name: DART-Windows

test: off
# notifications:
    #  - provider: Slack
    # incoming_webhook:
    #  secure: wQc/CYuw0WsjVvpj92QtP6//CzBNp/eFYpvlxiH6lIdhCbrh+cgQ3vExTygXJFA3xPg0attMwE/dOWipSS+vsk0EGsf0iipIaf/133/1RgQ=
    # on_build_success: false
    #  on_build_failure: true
    # on_build_status_changed: true
