version: "1.5.0-{build}"

platform: x64

init:
  - git config --global core.autocrlf input
    # TODO: Needs select-str to get version from package.json to save in env and update below
    #  - ps: Update-AppveyorBuild -Version "0.1.9-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))-Windows"
    #  - set BUILDVER=%APPVEYOR_BUILD_VERSION%-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))

cache:
     - node_modules
     - '%APPDATA%\npm-cache'
     - '%USERPROFILE%\.electron'
     - $HOME/.cache/electron
     - $HOME/.cache/electron-builder
     - $HOME/.npm/_prebuilds

clone_folder: c:\projects\dart

environment:
  access_token:
    secure: "0muZEDVGEpw8OhnyWFnafYkUgrt+7kl6MdWEA2guW8oLX6s3dMoRrhQjuF3Sbpi5"
    artifactName: DARTtest.Setup.0.1.8.$(APPVEYOR_BUILD_VERSION).$(APPVEYOR_REPO_COMMIT).exe

install:
  - ps: Install-Product node ''
  - git reset --hard HEAD
  - rm -rf node_modules
  - npm install --global npm@latest
    #  - npm install electron-builder@next # force install next version to test electron-builder
    #  - npm install --global jest
  - set NODE_PATH=C:\Users\appveyor\AppData\Roaming\npm\node_modules;%APPVEYOR_BUILD_FOLDER%/node_modules;%NODE_PATH%
  - set PATH=%APPVEYOR_BUILD_FOLDER%/node_modules/.bin;%APPVEYOR_BUILD_FOLDER%/node_modules/;C:\Users\appveyor\AppData\Roaming\npm\node_modules;%PATH%
  - npm install
    #  - npm test -- --runInBand

build_script:
    - electron-builder . --publish never

test: off
artifacts:
  - path: 'dist/*.exe'
    name: DART-Windows

after_build:
  - ps: Get-ChildItem .\dist\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName S3-public-deployment }

deploy:
  provider: S3
  name: S3-public-deployment
  access_key_id:
   secure: u4NH7eUlYuzO9hl5Hk/7P5K1qvo31iqZ19BW484x8BE=
  secret_access_key:
   secure: FMvYL/QE+0kHdy9L7GxtayJwx3KwQB3AA2mcIBqGGeEM0lqLLv4tq2b4wH9y3nJ8
  bucket: aptrust.public.download
  region: us-east-1
  set_public: true
  folder: DART
#  artifact: DART-Windows
  reduced_redundancy: true


# notifications:
    #  - provider: Slack
    # incoming_webhook:
    #  secure: wQc/CYuw0WsjVvpj92QtP6//CzBNp/eFYpvlxiH6lIdhCbrh+cgQ3vExTygXJFA3xPg0attMwE/dOWipSS+vsk0EGsf0iipIaf/133/1RgQ=
    # on_build_success: false
    #  on_build_failure: true
    # on_build_status_changed: true
